services:
  db:
    build: ./database
    container_name: olp-db
    env_file: ./server/env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./server
    container_name: olp-backend
    env_file: ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./client
    container_name: olp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

volumes:
  db-data:
